### ISSUE TITLE
Why you're creating theme in various components?

### ISSUE THREAD

**Issue by amitava82** [pranav-bharadwaj/react-ui-template#1]
https://github.com/pranav-bharadwaj/react-ui-template/blob/0b89f254b012e6545c013c55cdff49d8a02a0ba0/src/components/SidebarComponents/SidebarTopmenu.jsx#L24

I've seen you're creating theme in all over the places? Why? Why didn't you create one theme with all the configs? This looks like you did not understood the concepts.

**Comment by amitava82** [comment]
@pranav-bharadwaj

**Comment by Sanchari4us** [comment]
No sir it is created at first and I thought some cards are not required the same border and styles which overrides all card designs now it is fixed.

**Comment by pranav-bharadwaj** [comment]
No sir it is created at first and I thought some cards are not required the same border and styles which overrides all card designs now it is fixed.
